// Generated by https://quicktype.io

class PokemonColorModel {
  String? name;
  String? url;

  PokemonColorModel({
    this.name,
    this.url,
  });

  factory PokemonColorModel.fromMap(Map<String, dynamic> map) {
    return PokemonColorModel(
      name: map['name'],
      url: map['url'],
    );
  }
}